"""Check every configured URL and write an honest report.

This is the first thing to run. Every endpoint in config/sources.yaml is a guess or an
undertaking by its publisher, not something that has been confirmed from this machine.
The probe replaces guesses with facts.
"""
from __future__ import annotations

from pathlib import Path

import feedparser

from . import db, http, sources

REPORT = Path("config/probe-report.md")


def _classify(resp) -> tuple[str, str]:
    ctype = (resp.headers.get("content-type") or "").split(";")[0].strip()
    body = resp.text[:400_000]
    if resp.status_code >= 400:
        return "dead", f"HTTP {resp.status_code}"
    if "json" in ctype or body.lstrip()[:1] in "[{":
        return "json", f"{len(body)} bytes of JSON"
    if "xml" in ctype or "rss" in ctype or body.lstrip().startswith("<?xml"):
        parsed = feedparser.parse(body)
        n = len(parsed.entries)
        return ("feed", f"{n} entries") if n else ("empty-feed", "parsed but no entries")
    if "html" in ctype:
        return "html", "HTML page, needs a scraper"
    return "unknown", ctype or "no content-type"


def probe_one(source, fetcher) -> dict:
    url = source.url or source.fallback_html or source.alt_url
    result = {"source_id": source.id, "url": url}
    try:
        resp = fetcher.get(url)
        verdict, detail = _classify(resp)
        result.update(
            ok=verdict in {"json", "feed", "html"},
            http_status=resp.status_code,
            content_type=(resp.headers.get("content-type") or "").split(";")[0],
            verdict=verdict,
            detail=detail,
        )
    except Exception as exc:  # network, TLS, DNS - all interesting, none fatal
        result.update(
            ok=False,
            http_status=None,
            content_type=None,
            verdict="error",
            detail=f"{type(exc).__name__}: {exc}"[:300],
        )
    return result


def run(config_path="config/sources.yaml", db_path=db.DEFAULT_DB) -> list[dict]:
    cfg = sources.load(config_path)
    fetcher = http.Fetcher(cfg.user_agent, cfg.timeout, cfg.delay)
    conn = db.connect(db_path)
    results = []
    for src in cfg.sources:
        if not src.probeable:
            results.append(
                {
                    "source_id": src.id,
                    "url": None,
                    "ok": False,
                    "http_status": None,
                    "content_type": None,
                    "verdict": "no-url",
                    "detail": src.status,
                }
            )
            continue
        r = probe_one(src, fetcher)
        db.record_probe(
            conn, r["source_id"], r["ok"], r["http_status"],
            r["content_type"], r["verdict"], r["detail"],
        )
        results.append(r)
        print(f"{r['verdict']:>11}  {src.id:<32} {r['detail']}")
    conn.commit()
    write_report(cfg, results)
    return results


def write_report(cfg, results) -> None:
    by_id = {r["source_id"]: r for r in results}
    lines = [
        "# Probe report",
        "",
        "Generated by `python -m leaside.cli probe`. This is the only file in the repo",
        "that records verified facts about the sources. Everything else is intent.",
        "",
        "| source | configured status | probe verdict | detail |",
        "| --- | --- | --- | --- |",
    ]
    for src in cfg.sources:
        r = by_id.get(src.id, {})
        lines.append(
            f"| `{src.id}` | {src.status} | **{r.get('verdict', '-')}** | "
            f"{str(r.get('detail', '')).replace('|', '/')[:120]} |"
        )
    working = [r for r in results if r.get("ok")]
    lines += [
        "",
        f"**{len(working)} of {len(results)} sources responded usefully.**",
    ]
    if not working:
        lines += [
            "",
            "> Every source errored. That almost always means the machine running the probe",
            "> has no outbound internet access, not that every publisher is down. Re-run it",
            "> from a normal network before changing anything in `config/sources.yaml`.",
        ]
    lines += [
        "",
        "Next: promote every `feed` and `json` verdict to `status: documented` in",
        "`config/sources.yaml`, and write a scraper or drop every `error` and `dead` one.",
    ]
    REPORT.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {REPORT}")
